# -*- coding: utf-8 -*-
"""Sentence Similarity Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y8Ajz_KB6tomFtSED-Oj84rzFsKuGsc3
"""

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer,util

#Load the model
model = SentenceTransformer('all-MiniLM-L6-v2')

#Take input from user
text1 = input("Enter text1: ")
text2 = input("Enter text2: ")

#Convert text to embeddings
embedding1 = model.encode(text1)
embedding1 = model.encode(text2)

# Calculate Simularity
similarity = util.cos_sim(embedding1,embedding2)

#Show result
print("\n Similarity Score: ",round(float(similarity),2))

if similarity>0.75:
  print("Similarity Level:High")
elif similarity>0.4:
  print("Similarity Level:Medium")
else :
  print("Similarity Level:Low")

